### ISSUE TITLE
room evacuation

### ISSUE THREAD

**Issue by jjj333-p** [jjj333-p/dendrite-admin-interface#1]
![image](https://github.com/jjj333-p/dendrite-admin-interface/assets/94018608/7bc2400c-7138-467f-9cec-85127a0bb5d9)

**Comment by jjj333-p** [comment]
im picturing room evacuation command to by default also purgeroom, perhaps with a flag to not.

not entirely sure what they mean by regexp

**Comment by timaeos** [comment]
Sorry, missed that you had already created an issue for this. Here is what I had posted on the other issue

As mentioned in the #dendrite:matrix.org room:

Having a regular expression format that allows for mass user deletion / purging would be useful for managing spam account abuse. I would preferably want there to be a confirmation step that shows example accounts (<20) that are going to be purged or deleted prior to performing the purge because malformed RegEx mishaps are bound to happen.

Similarly, mass evacuations of rooms would be helpful for moderation.

**Comment by jjj333-p** [comment]
> oh hm i never would have thought about that. i kinda like that idea since many spambot scripts will do `@spambot_[randomstring]:server.tld` which could be reasonably picked up by regex. re: my confusion evident in #1 
> 
> as for mass evacuations, assuming you dont mean evacuating multiple rooms at once that is already a natively supported admin endpoint and of course this will have it, see #1

**Comment by jjj333-p** [comment]
(moved regex based user deletion to https://github.com/jjj333-p/dendrite-admin-interface/issues/9 )
